### ISSUE TITLE
Some emails are not processed if we get an exception from mailgun

### ISSUE THREAD

**Issue by brunoroux** [tehplague/swiftmailer-mailgun-bundle#23]
I'm using the `spool: { type: memory }` that processes the spool on kernel.terminate event.
The problem I'm having is : 
If you have 3 emails in spool but for whatever reason mail#2 throws an exception while attempting to send it, then mail#3 never get processed.

I think a good solution might be to add a try / catch around sendMessage call in MailgunTransport. This silences the exception and that might be bad but it would avoid unprocessed emails. WDYT ?

**Comment by Nyholm** [comment]
This is a really valid point. But Im not sure it is within the scope of the bundle. What exception might occur? Is it related to the Mailgun library? How does other mail transports do? Ie the smtp transport?

**Comment by tehplague** [comment]
What about temporary errors, e.g. 4xx SMTP responses? How would a try-catch approach react to them? By the way, @Nyholm, you are right - what does the SMTP transport do about them?

Let's investigate this before making a decision on how to catch transport errors.

**Comment by brunoroux** [comment]
These errors are totally Mailgun related.

The one I had was MissingEndpoint. But there are quite a few others : MissingRequiredParameter, InvalidCredentials and GenericHTTPError.

The Mailgun library acts as follows : 
If http response is 200 => everything is ok
Otherwise: throw an exception.

Other transports do not use Exceptions. (That's why I proposed catching exceptions).
The send method returns the number of sent emails. So if the send fails, it just returns 0.

**Comment by Nyholm** [comment]
The other transports [do throw exceptions](https://github.com/swiftmailer/swiftmailer/blob/v5.4.2/lib/classes/Swift/Transport/AbstractSmtpTransport.php#L175-L181). However, I think we MUST catch Mailgun exceptions and take appropriate actions. I would also prefer if we catch all other exceptions like @brunoroux suggesting. 

We should aslo implement the return value and the $failedRecipients better. 

Would you mind creating a PR?

**Comment by brunoroux** [comment]
Will do
