### ISSUE TITLE
Update return value for send()

### ISSUE THREAD

**Issue by Nyholm** [tehplague/swiftmailer-mailgun-bundle#24]
While investigating for #23 I found that the SMTP transport is returning the number of the sent emails. We are always returning 1 but they are returning a number of all recipient. 

We should update that. 

Ref: https://github.com/swiftmailer/swiftmailer/blob/v5.4.2/lib/classes/Swift/Transport/AbstractSmtpTransport.php#L168-L199

**Comment by bartek1234321** [comment]
What do you think about return response which you get from mailgun api?

**Comment by Nyholm** [comment]
Closed by #30
