### ISSUE TITLE
Mailgun availability in container

### ISSUE THREAD

**Issue by placid2000** [tehplague/swiftmailer-mailgun-bundle#27]
Hi

I'm on symfony 2.8 and I installed mailgun according to the installation instruction on: https://github.com/tehplague/swiftmailer-mailgun-bundle

I trying to use `$container->get('mailgun.library')` in a self created Symfony command but I'm getting an exception:

```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
You have requested a non-existent service "mailgun.library"
```

Executing these commands `php app/console debug:container mailgun` and `php app/console debug:container mailgun.library` also throw the exception:

```
[InvalidArgumentException]
No services found that match "mailgun".
```

Any idea what the problem could be?

PS: actually I'm not sure if it is the right place to open this issue.

**Comment by Nyholm** [comment]
Hi. 

Yes, it is the right place to report this issue. Thank you. 

It seams like you have note added the bundle in the AppKernel.php. If so, have you cleared the cache?

**Comment by placid2000** [comment]
Actually I did add the bundle to AppKernel.php and also cleared cache. Interesstingly the service exists over Webserver requests. It is not found only over cli executions.. There might be something wrong with my environement in general.

**Comment by Nyholm** [comment]
Did you manage to solve this issue? Can it be closed?

**Comment by placid2000** [comment]
Somehow it worked. Unfortunately I don't remember how I solved. Hence, it can be closed.
