### ISSUE TITLE
httpResponseCode 404

### ISSUE THREAD

**Issue by Chensienyong** [tehplague/swiftmailer-mailgun-bundle#28]
so i use this bundle for my symfony 3 for sending email through mailgun.
I set as usage but i always getting 404 httpResponseCode in RestClient.

**Comment by Nyholm** [comment]
Interesting. By best guess is that you have wrong api_domain or secret.

**Comment by Chensienyong** [comment]
i have double check key api and domain, nothing wrong with both of them.

i tried to print the request in post function (RestClient.php) and i notice the path contain my domain + "/messages.mime".

**Comment by Nyholm** [comment]
Okey, glad you found it. =)
