### ISSUE TITLE
can we use tags?

### ISSUE THREAD

**Issue by Tr4cer0ute** [tehplague/swiftmailer-mailgun-bundle#36]
Hi. We are looking to set tags under SwiftMailer. is this supported? if yes how can we use them?
Best

**Comment by Nyholm** [comment]
Sure, you can just add custom "o:tags" header if I recall correctly

**Comment by Tr4cer0ute** [comment]
@Nyholm  Thanks for quick reply

Using just ->setTags() ?

$message = \Swift_Message::newInstance()
        ->setSubject('Hello Email')
        ->setFrom('send@example.com')
        ->setTo('recipient@example.com')
        ->setBody(
            $this->renderView(
                'HelloBundle:Hello:email.txt.twig',
                array('name' => $name)
            )
        )
    ;

**Comment by Nyholm** [comment]
No, SwiftMailer does not support tags. 

But you can add a header to the message. The header is called `o:tag`. 

Something like this (not tested):

```php
$message = \Swift_Message::newInstance()
->setSubject('Hello Email')
->setFrom('send@example.com')
->setTo('recipient@example.com')
->addHeader('o:tag', 'My mailgun tag')
->setBody(
$this->renderView(
'HelloBundle:Hello:email.txt.twig',
array('name' => $name)
)
);
```

**Comment by Tr4cer0ute** [comment]
yes but  addHeader method is not supported

**Comment by Nyholm** [comment]
Sorry, Use getHeaders first. See the SwiftDocumentation: http://swiftmailer.org/docs/headers.html#header-types
