### ISSUE TITLE
Bad instantiation of mailgun library 

### ISSUE THREAD

**Issue by jazzo221** [tehplague/swiftmailer-mailgun-bundle#41]
You create instance of Mailgun\Mailgun class through constructor but you need to use Mailgun\Mailgun::configure.
Without that any api call wont work when you get the "mailgun.library" service.

`$configurator = new HttpClientConfigurator();
$configurator->setApiKey('key-example');
$mg = Mailgun::configure($configurator, new ArrayHydator());
$data = $mg->domains()->show('example.com');`

[https://github.com/mailgun/mailgun-php/issues/346](url)

**Comment by Nyholm** [comment]
Thank you. Have a look at #40. Please review and try it. All feedback is appreciated.
