### ISSUE TITLE
Unrecognized option "http_client" under "mailgun"

### ISSUE THREAD

**Issue by develaper** [tehplague/swiftmailer-mailgun-bundle#46]
After some tries we managed to have everything working (locally and in production) smoothly with Symfony version 3.1.10 + swiftmailer + MailgunBundle + httplug-bundle + Guzzle 6 Adapter.
But if we try to make a composer update or composer install then we get this error:

`[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "http_client" under "mailgun"     `                         
                                                                                 

`Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception`

                                                                                     
 ` [RuntimeException]                                                                 
  An error occurred when executing the "'cache:clear --no-warmup'" command:   `       
                                                                                     
  `  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]    
    Unrecognized option "http_client" under "mailgun"   `

After checking both installations it is quite clear that there is a huge difference between each composer.lock

Here is a part of the working one:

{
            "name": "cspoo/swiftmailer-mailgun-bundle",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/tehplague/swiftmailer-mailgun-bundle.git",
                "reference": "21efc86edfa7b5d47fc944a821ee400b9af2f2d6"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/tehplague/swiftmailer-mailgun-bundle/zipball/21efc86edfa7b5d47fc944a821ee400b9af2f2d6",
                "reference": "21efc86edfa7b5d47fc944a821ee400b9af2f2d6",
                "shasum": ""
            },
            "require": {
                "mailgun/mailgun-php": "^2.0",
                "php": "^5.5 || ^7.0",
                "swiftmailer/swiftmailer": "^5.0",
                "symfony/dependency-injection": "^2.7 || ^3.0"
            },

And here is the "equivalent" in the installation that doesn't work:

{
            "name": "cspoo/swiftmailer-mailgun-bundle",
            "version": "0.2.0",
            "target-dir": "cspoo/Swiftmailer/MailgunBundle",
            "source": {
                "type": "git",
                "url": "https://github.com/tehplague/swiftmailer-mailgun-bundle.git",
                "reference": "a23acf5fc4410c6abc9843dee82013d5f89a2426"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/tehplague/swiftmailer-mailgun-bundle/zipball/a23acf5fc4410c6abc9843dee82013d5f89a2426",
                "reference": "a23acf5fc4410c6abc9843dee82013d5f89a2426",
                "shasum": ""
            },
            "require": {
                "mailgun/mailgun-php": ">=1.7",
                "php": ">=5.3",
                "swiftmailer/swiftmailer": "~5.0, >=4.0"
            },

And here is the requiere statement of the composer.json:

    "require": {
        "php": ">=5.5.9",
        "symfony/symfony": "3.1.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "symfony/polyfill-apcu": "^1.0",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "hwi/oauth-bundle": "^0.5.1",
        "illuminate/database": "^5.4",
        "knplabs/knp-paginator-bundle": "^2.5",
        "yceruto/breadcrumbs-bundle": "^1.0",
        "cspoo/swiftmailer-mailgun-bundle": "dev-master",
        "php-http/guzzle6-adapter": "^1.1",
        "php-http/httplug-bundle": "^1.4"
    },

I understand that "cspoo/swiftmailer-mailgun-bundle": "dev-master" requieres the last version in the dev-master branch and it creates an inconsistency between versions and dependencies.
Do you have any clue about how shall we procede to avoid these error and keep our project updated?

**Comment by Nyholm** [comment]
make sure you require `"cspoo/swiftmailer-mailgun-bundle": "0.4.0"` and you will be all fine. In the composer.lock that does not work you were using 0.2.0

**Comment by develaper** [comment]
Thanks @Nyholm !! It worked like a charm.

**Comment by develaper** [comment]
Here we find ourselves in the same point again.
As said before we have an installation working properly but one we try to do a new composer install a ServiceNotFoundException raises:
` "You have requested a non-existent service "httplug.client". "`
Here is our requiere statement of the composer.json file:
`    "require": {
        "php": ">=5.5.9",
        "symfony/symfony": "3.1.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "symfony/polyfill-apcu": "^1.0",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "hwi/oauth-bundle": "^0.5.1",
        "illuminate/database": "^5.4",
        "knplabs/knp-paginator-bundle": "^2.5",
        "yceruto/breadcrumbs-bundle": "^1.0",
        "cspoo/swiftmailer-mailgun-bundle": "0.4.0",
        "php-http/guzzle6-adapter": "^1.1.1",
        "php-http/httplug-bundle": "^1.6"
    },`
This change in the config.yml helps to complete the installation:
` cspoo_swiftmailer_mailgun:

     key: "key-xxxxxxxxxxxxxxxxxxxx"

     domain: "mydomain.net"

-    http_client: 'httplug.client' # Optional. Defaults to null and uses dicovery to find client.

+    #http_client: 'httplug.client' # Optional. Defaults to null and uses dicovery to find client.`

But obviously the mailer won't work as expected.
I guess that I am missing something in how does the composer works.
Any guidance about how to make it work will be very much appreciated.

**Comment by develaper** [comment]
I will open a new issue for the seek of clarity adding as much info as possible.
