### ISSUE TITLE
Attaching custom data to messages

### ISSUE THREAD

**Issue by s4astliv** [tehplague/swiftmailer-mailgun-bundle#47]
Hey.

I would like to attach custom data to the message as described in Mailgun docs:

http://mg-documentation.readthedocs.io/en/latest/user_manual.html#attaching-data-to-messages

According to the docs:

> The data will be represented as a header within the email, X-Mailgun-Variables. To add this header to your message:
> API: Pass the following parameter, “v:my-custom-data” => “{“my_message_id”: 123}”.
> SMTP: Add the following header to your email, “X-Mailgun-Variables: {“my_message_id”: 123}”.

Is it possible to achieve this with this bundle?

What I have tried is that I added a header to the message (basically used SMTP approach, but bundle is using API). I can see this header in the message:

`X-Mailgun-Variables: {“my_message_id”: 123}`

However in the mailgun logs `user-variables` is empty.

`"user-variables": {},`

Would anyone be able to advise on this please?

Thank you.

**Comment by Nyholm** [comment]
Sure, Just add headers to the Swift message. 

```php
$message = \Swift_Message::newInstance('Test');
$message->setFrom(['from@Example' => 'From address']);
$message->setTo(['tobias.nyholm@gmail.com' => 'To address']);

$headers = $message->getHeaders();
$headers->addTextHeader('X-Mailgun-Variables', json_encode(['foobar' => 'baz']));

$messageBody = 'Look at <b>this</b> HTML body!';
$message->setBody($messageBody, 'text/html');

$this->get('swiftmailer.mailer')->send($message);
```

**Comment by s4astliv** [comment]
Thank you! This helped me to find the problem.

The problem was because of the quotes (") around message_id.

Wrong: X-Mailgun-Variables: {“my_message_id”: 123}
Correct: X-Mailgun-Variables: {"my_message_id": 123}
