### ISSUE TITLE
SwiftMailer 6

### ISSUE THREAD

**Issue by tchapi** [tehplague/swiftmailer-mailgun-bundle#48]
Hi, 
I need to use SwiftMailer ^6.0 in my project but your bundle requires the 5.0 version — is this compatible ? In this case, could you change the requirements for something like ^5.0 || ^6.0 ?

Thanks a lot !

**Comment by Nyholm** [comment]
Hi, 
I do not know. I have not followed the changes in Swift. It is most likely compatible. Could you investigate that? 

Ie, see the change logs and find out if we are effected.

**Comment by tchapi** [comment]
I can have a look. It seems you have a test suite that should cover things up — how do you run it (it's not on the readme) ?

thanks

**Comment by tchapi** [comment]
`./vendor/phpunit/phpunit/phpunit` should suffice I guess

**Comment by tchapi** [comment]
Ok — there are some breaking changes. I will make a PR that make the tests run correctly

**Comment by pculka** [comment]
Can you please merge this fix? I need this too, Swiftmailer 6 is going to be required also in Symfony4

**Comment by stevechilds** [comment]
This is fine if you're using SwiftMailer 6, we're not. Surely it would have been better to support 5 and 6 at the same time?

**Comment by tchapi** [comment]
Version 0.4.0 is still the latest release and is made for SwiftMailer 5 so you shouldn't have any problem using this bundle if you're still using SW 5.

**Comment by stevechilds** [comment]
Erm, version 1.0.0 is the release installed via composer if you don't specify 0.4.0 as the version number?

Do you plan to maintain SW 5 support for a while as the 1.0.0 version also bumps the PHP version up to 7 as well, you're going to leave a lot of older Symfony 2.x projects behind if you don't. 

And yes, I know we should be upgrading to 3, its just not that easy when you got a massive system to maintain ;) We will be jumping to PHP 7 shortly though, which will help.
