### ISSUE TITLE
Incompatibility with Symfony 4 - Deprecated DefinitionDecorator

### ISSUE THREAD

**Issue by renatoaraujo** [tehplague/swiftmailer-mailgun-bundle#57]
I am trying to install and use this bundle in Symfony 4, but I am getting the following error:

PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DefinitionDecorator" from namespace "Symfony\Component\DependencyInjection".
Did you forget a "use" statement for another namespace? in [...]/cspooSwiftmailerMailgunExtension.php:36

According to the Symfony documentation DefinitionDecorator class has been deprecated since 3.3 and removed in 4.0. This class needs to be replaced by **ChildDefinition**.

https://github.com/symfony/symfony/blob/master/UPGRADE-4.0.md

I will open a new PR for this issue. 

Cheers.

**Comment by Nyholm** [comment]
Fixed by #55
