### ISSUE TITLE
Attachments?

### ISSUE THREAD

**Issue by robcaw** [tehplague/swiftmailer-mailgun-bundle#6]
Does this transporter support attachments?

**Comment by tehplague** [comment]
Currently not, but you are free to provide an implementation that can be merged into the bundle :-)

**Comment by Nyholm** [comment]
I will argue differently. Attachments do work. 

``` php
$message = \Swift_Message::newInstance('Test attachment');
$message->setFrom(array('from@example.com' => 'From address'));
$message->setTo(array('tobias@happyr.com' => 'To address'));

$messageBody = 'Look at <b>this</b> PDF!.';
$message->setBody($messageBody, 'text/html');

$attachment = new \Swift_Attachment();
$attachment->setFile(
    new \Swift_ByteStream_FileByteStream('/Users/tobias/Downloads/test.pdf'),
    'application/pdf'
);
$message->attach($attachment);

$this->get('swiftmailer.mailer.direct_mailer')->send($message);
```

Tested with Swiftmailer 5.4

**Comment by robcaw** [comment]
But if @tehplague hasn't implemented it yet, how is the attachment being mapped to the mailgun api?

**Comment by Nyholm** [comment]
It's handled by `$message->toString()`.

**Comment by tehplague** [comment]
Attachments weren't needed at the time I wrote this extension, so I presumed that they actually wouldn't work. But if @Nyholm proves otherwise, I consider this as fixed ;)

**Comment by exuperok** [comment]
+1

**Comment by TrogWarZ** [comment]
It seems that doesn't working. This example code doesn't trigger any errors or throws any exceptions – it just returns but request doesn't go to the MailGun.

Any thoughts?

```php
$mailer  = /* Service '@mailer' from app/config.yml */;
$pdf     = /* Absolute path to PDF file */

// Test #1
$attach = \Swift_Attachment::fromPath($pdf);
// Test #2
$attach = new \Swift_Attachment();
$attach = $attach->setFile(new \Swift_ByteStream_FileByteStream($pdf), 'application/pdf');

$message = \Swift_Message::newInstance();
$message->setFrom('from@example.com', 'John Doe');
$message->setSubject('Testing PDF attachments');
$message->setTo('to@example.com', 'Agatha Smith');
$message->setBody('Do you see PDF file here?', 'text/html', 'utf-8');
$message->attach($attach);
$mailer->send($message); // @return 1
```

**Comment by tehplague** [comment]
`swiftmailer.mailer.direct_mailer` is specific to @Nyholm's use case. You need to specify the correct mailer depending on your Swiftmailer configuration in Symfony.
Does your code work when trying to send an email without an attachment? If not, there might be an issue with the Mailgun part of your configuration.

**Comment by TrogWarZ** [comment]
Got it about service, thanks!

Yes, if i delete `$message->attach($attach);` line, message sent successfully and correctly.

**Comment by TrogWarZ** [comment]
Any news here? I'm still getting situation that mails doesn't sent if i try to attach any file (pdf/img).

**Comment by Sybio** [comment]
Also facing this issue...
